export enum MutationType {
  ADD_PROJECT = 'ADD_PROJECT',
  EDIT_PROJECT = 'EDIT_PROJECT',
  REMOVE_PROJECT = 'REMOVE_PROJECT',
  REMOVE_ALL_PROJECTS = 'REMOVE_ALL_PROJECTS',


  ADD_TODO = 'ADD_TODO',
  EDIT_TODO = 'EDIT_TODO',
  REMOVE_TODO = 'REMOVE_TODO',
  REMOVE_ALL_TODOS = 'REMOVE_ALL_TODOS',
}
